name: Manual Dependabot Trigger

on:
  workflow_dispatch:

jobs:
  trigger-dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Dependabot
        uses: dependabot/fetch-metadata@v1
